title: W3C Guidebook
baseurl: /guide
remote_theme: w3c/w3c-jekyll-theme
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: false
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
optional_front_matter:
  remove_originals: true
toc:
  max_level: 3
